Repository peiva-git/deep_learning_project, pull requests merged in 2023-10, with the labels that each got.

#8 Simple model added
  README.md
  dlproject/__init__.py
  dlproject/data/__init__.py
  dlproject/data/mnist_dataset.py
  dlproject/models/__init__.py
  dlproject/models/simple_model.py
  requirements.txt
  simple_model.ipynb
  usage_example.ipynb
Labels: enhancement

#12 Corretto import notebook
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  dlproject/__init__.py
  dlproject/data/__init__.py
  dlproject/models/__init__.py
  simple_model.ipynb
Labels: bug, enhancement

#10 9 add project proposal document
  ProjectProposal_CalandraPelizon.pdf
  README.md
  report/front/header.tex
  report/img/units_sigillo_pantone-534.pdf
  report/main.tex
  report/sections/abstract.tex
Labels: documentation
