Repository peiva-git/deep_learning_project, pull requests merged in 2023-11, with the labels that each got.

#21 Update simple_model.ipynb
  simple_model.ipynb
Labels: bug, enhancement

#24 Added `simple_vae.ipynb`
  .idea/deep_learning_project.iml
  .idea/misc.xml
  dlproject/data/mnist_dataset.py
  dlproject/models/__init__.py
  dlproject/models/simple_autoencoder.py
  dlproject/models/simple_vae.py
  simple_model.ipynb
  simple_vae.ipynb
Labels: enhancement

#23 22 add image plots to simple modelipynb
  simple_model.ipynb
Labels: enhancement

#27 Corrected bugs
  simple_model.ipynb
Labels: bug

#31 Updated `README.md`
  README.md
Labels: enhancement

#28 Agiunta capacità di salvataggio modelli addestrati
  dlproject/models/simple_autoencoder.py
  requirements.txt
  simple_model.ipynb
  simple_vae.ipynb
Labels: enhancement

#39 25 train and test the simple autoencoder model with the cifar10 dataset
  .idea/misc.xml
  dlproject/models/simple_autoencoder.py
  simple_model.ipynb
Labels: enhancement

#45 Addestramento `SimpleVAE`
  dlproject/models/simple_vae.py
  models/vae_mlp_mnist.keras
  simple_vae.ipynb
Labels: bug, documentation, enhancement

#49 Added visualize.py
  dlproject/data/visualize.py
Labels: enhancement

#50 Add VAE visualization
  conda/tf-gpu.yml
  dlproject/data/__init__.py
  dlproject/data/visualize.py
  dlproject/models/simple_vae.py
  images/vae_generated_digits.png
  images/vae_scatter.png
  simple_model.ipynb
  simple_vae.ipynb
Labels: bug, enhancement

#59 Refactor `simple_vae.ipynb`
  dlproject/data/__init__.py
  dlproject/data/visualize.py
  models/vae_decoder_weights_mnist.keras
  models/vae_encoder_weights_mnist.keras
  models/vae_mlp_mnist.keras
  models/vae_mlp_weights_mnist.keras
  simple_vae_mnist.ipynb
Labels: bug, enhancement

#62 Added Restormer notebook
  Restormer.ipynb
Labels: enhancement

#53 Aggiunto file configurazione
  .gitattributes
  simple_model.ipynb
Labels: enhancement

#64 63 new renoir dataset
  dlproject/data/__init__.py
  dlproject/data/preprocess_renoir_dataset.py
  dlproject/data/renoir_dataset.py
Labels: enhancement

#67 65 refactor delete renoir_dataset.py
  dlproject/data/renoir_dataset.py
Labels: enhancement

#69 SimpleVAE evaluation
  dlproject/__init__.py
  dlproject/data/cifar_dataset.py
  dlproject/evaluation.py
  requirements.txt
  simple_model.ipynb
  simple_vae_cifar10.ipynb
  simple_vae_mnist.ipynb
Labels: enhancement

#73 Updated README.md
  README.md
  denoising_simple_vae_mnist.ipynb
Labels: documentation

#74 68 restormer evaluation
  .idea/deep_learning_project.iml
  .idea/misc.xml
  dlproject/data/visualize.py
  dlproject/evaluation.py
  restormer_evaluation.ipynb
  simple_model.ipynb
  simple_vae_cifar10.ipynb
  simple_vae_mnist.ipynb
Labels: enhancement

#75 70 aggiunta modelli tradizionali
  dlproject/data/image_utils.py
  tools/filtering.py
Labels: enhancement

#76 SimpleVAE con rumore
  denoising_simple_vae_mnist.ipynb
  dlproject/data/mnist_dataset.py
  images/vae_generated_noisy_mnist.png
  images/vae_scatter_noisy_mnist.png
  models/vae_decoder_weights_noisy_mnist.keras
  models/vae_encoder_weights_noisy_mnist.keras
  models/vae_mlp_weights_noisy_mnist.keras
  simple_vae_mnist.ipynb
Labels: enhancement

#78 Create restormer_PSNR_SSIM_results.txt
  results/restormer_PSNR_SSIM_results.txt
Labels: enhancement

#86 Aggiunte immagini RENOIR
  images/clean_patch_6.png
  images/noisy_patch_6.png
  images/restored_patch_6.png
Labels: documentation, enhancement
